# Algo selection
algo: 'DQN'

# Environment settings
env:
  name: 'CartPole-v1'
  max_steps: 500

# Neural network architecture
network:
  hidden_size: 128

# RL hyperparameters
hyperparameters:
  lr: 3.0e-4
  gamma: 0.99
  tau: 0.005
  buffer_capacity: 10000
  batch_size: 128

# Exploration parameters (epsilon greedy)
exploration:
  max_epsilon: 0.9
  min_epsilon: 0.01
  decay_rate: 2000

# training parameters
training:
  n_episode: 700
  seed: 19 # run 5 times with different seeds 15, 16, 17, 18, 19
  save_dir: './results/DQN_cartpole'

# Experiment tracking & video recording settings
logging:
  track: true           # Set to true to enable Weights & Biases tracking
  wandb_project: 'Ryan-RL'
  group: 'CartPole-v1_DQN' # group name for W&B multi-seed aggregation
  capture_video: false   # Set to true to record MP4 videos
  video_trigger: 100     # Record video every N episodes