# Algo selection
algo: 'VecDuelingDQN'  # choose from VecDQN, VecDoubleDQN and VecDuelingDQN

# Environment settings
env:
  name: 'LunarLander-v3'
  num_envs: 4

# Neural network architecture
network:
  hidden_size: 256

# RL hyperparameters
hyperparameters:
  lr: 3.0e-4
  gamma: 0.99
  tau: 0.005
  buffer_capacity: 50000
  batch_size: 128

# Exploration parameters (epsilon greedy)
exploration:
  max_epsilon: 1.0
  min_epsilon: 0.05
  decay_rate: 10000

# training parameters
training:
  total_timesteps: 300000
  seed: 19 # run 5 times with different seeds 15, 16, 17, 18, 19
  save_dir: './results/DuelingDQN_LunarLander'

# Experiment tracking & video recording settings
logging:
  track: true           # Set to true to enable Weights & Biases tracking
  wandb_project: 'Ryan-RL'
  group: 'LunarLander_DuelingDQN' # group name for W&B multi-seed aggregation
  # capture_video: false   # Set to true to record MP4 videos
  # video_trigger: 100     # Record video every N episodes